project_id = "auto-ocr"

# [db.vault]
# secret_key = "env(SECRET_VALUE)"

[db.migrations]
enabled = true
schema_paths = [
  "./schemas/_init.sql",
  "./schemas/*.sql",
  "./schemas/documents/*.sql",
]

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[experimental]
compute = true

[compute.docling-ocr]
runtime = "dockerfile"
size = "4gb"
exposure = "public"

[compute.ocr-processor]
runtime = "dockerfile"
size = "4gb"
exposure = "public"
